### ISSUE TITLE
Can no longer create a new world after recent update

### ISSUE THREAD

**Issue by TheEventHorizon** [Jiexgx/Create_Mortar#2]
Can no longer create a new world after recent update. I have attached the crash log.

Running Forge 47.2.30
Minecraft version 1.20.1
[Crash log.txt](https://github.com/Jiexgx/Create_Mortar/files/15210717/Crash.log.txt)

**Comment by Jiexgx** [comment]
Should be fixed in the 0.2.3 please update

**Comment by TheEventHorizon** [comment]
I can confirm its working. Thank you so much for the quick response!
